export interface absareq {
    ABSAREQNO: number,
    PROJLINK: string ,
    TITLE: string,
    REGION: string ,
    PROVREGION: string ,
    MULTISITES: string ,
    VARIOUSSITES: string ,
    ONEVIEW: string ,
    KNOWNAS: string ,
    SITES: string ,
    DETAILS: string 
    PROPSTARTDATE: string,
    PROPENDDATE:string,
    STATUS: string ,
    CIPNAME: string,
    CIPCODE: string,
    CIPGROUP: string,
    ESTIMATEDBUDGET: string ,
    BASELINEBUDGET: string ,
    BUDGETDIF: string ,
    QUOTATION: string ,
    FUNDERS: []
    FUNDING: string ,
    AUTHORIZER: string ,
    PMANAGER: string ,
    EPRIORITY: string ,
    CAPEX_OPEX: string ,
    DISCRETIONARY: string ,
    IM_POSITION: string ,
    RETROSPECTIVE: string,
    PLANSTATUS: string ,
    SITENOTES: string ,
    LEASED_FREE: string ,
    LEASEEND: string ,
    ENDOFLIFE: string ,
    PONUMBER: string ,
    BUILDINGID: string ,
    FORECAST_START: string ,
    FORECAST_END: string,
    QUARTER: string ,
    SCOPE: string ,
    BOQ: string ,
    COSTS: string ,
    RATING: string ,
    PO: string ,
    APPROVAL: string ,
    APPROVALSTATUS:string ,
    APPROVAL_MOTIVATE:string ,
    APPROVAL_STATUS:string ,
    APPROVAL_DATE:string ,
    APPROVAL_SUBMITDATE:string ,
    APPROVED_AMT:string ,
    APPROVAL_NOTE:string ,
    CONTINGENCY: string ,
    IMPLEMENT: string ,
    PPRACT_COMPLETE: string ,
    OHSRISK: string ,
    DONEBY: string ,
    CLIENTAPPROVAL: string,
    INVSUBMITTED: string ,
    PROGRESS: string,
    CIPLINEBUDGET: string ,
    PORTFOLIOMGR: string ,
    ACCOUNTANT: string ,
    BACKGROUND: string ,
    APPREQLINK: string ,
    APPROVALTOLEGAL: string,
    APPROVEDBYLEGAL: string,
    APPTOBFMLEGAL: string,
    APPBYBFMLEGAL: string,
    PODATE: string,
    POVALUE: number,

}