export interface Approval {
    ABSAREQNO: string,
    PROJLINK:'',
    TITLE: string,
    BASELINEBUDGET:number,
    APPROVAL_MOTIVATE: string,
    APPROVAL_STATUS: string,
    APPROVAL_SUBMITDATE: string,
    APPROVAL_DATE: string,
    APPROVED_AMT: number,
    APPROVAL_NOTE: string,
    PONUMBER: string,
    APPROVALTOLEGAL: string,
    APPROVEDBYLEGAL: string,
    APPTOBFMLEGAL: string,
    APPBYBFMLEGAL: string,      
    POVALUE:number,
    PODATE: string,
  }
