export interface Progress {
    REFERENCE: string,
    multisite:string,
    PHASE: string,
    PROG01: string,
    PROG02: string,
    PROG03: string,
    PROG04: string,
    PROG05: string,
    PROG06: string,
    PROG07: string,
    PROG08: string,
    PROG09: string,
    PROG10: string,
    PROPSTARTDATE: string,
    PROPENDDATE:string,
    FORECAST_START: string,
    FORECAST_END: string,
    TRACKNOTE:string,
}